server:
  port: 1003

eureka:
  client:
    serviceUrl:
      defaultZone: http://richard:richard@localhost:1001/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.saigon.services.application

--- 
spring:
  config:
    activate:
      on-profile:
      - localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://richard:richard@localhost:1001/eureka/

--- 
spring:
  config:
    activate:
      on-profile:
      - development
eureka:
  client:
    serviceUrl:
      defaultZone: http://richard:richard@richardvu.com:8020/eureka/

--- 
spring:
  config:
    activate:
      on-profile:
      - production
eureka:
  client:
    serviceUrl:
      defaultZone: http://richard:richard@richardvu.com:8022/eureka/